-----20/09/2015 12:48
Unable to add code to mapping:
Traceback (most recent call last):
  File "C:\Users\cekin\Documents\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 174, in exclude_tfc
    result = sql.exclude_tfc(system,tfc,exclusion,user.email)
AttributeError: 'str' object has no attribute 'email'
-----20/09/2015 12:49
Unable to add code to mapping:
Traceback (most recent call last):
  File "C:\Users\cekin\Documents\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 174, in exclude_tfc
    result = sql.exclude_tfc(system,tfc,exclusion,user.email)
AttributeError: 'str' object has no attribute 'email'
-----20/09/2015 12:53
Unable to add code to mapping:
Traceback (most recent call last):
  File "C:\Users\cekin\Documents\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 174, in exclude_tfc
    raise Exception('message')
Exception: message
-----21/09/2015 00:41
Error getting global codes together:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 102, in global_table
    L['result'].append([r['GlobalCode'], r['Description'], r['Sample'], r['Type'], r['Analyte'], r['PrimaryLibrary'], r['SubSection'], r['Department']])
TypeError: string indices must be integers, not str
-----01/10/2015 18:48
Error looking up TLC detail:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 100, in system_info
    result = sql.exec_stored_procedure('spGlobalsApp_SystemOverview', [system,section])
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 19, in exec_stored_procedure
    cursor.execute(sql)
ProgrammingError: ('42000', "[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Could not find stored procedure 'spGlobalsApp_SystemOverview'. (2812) (SQLExecDirectW)")
-----07/10/2015 23:32
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 218, in dashboard
    data = sql.exec_stored_procedure('spGlobalsApp_AllSystemStats')
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 19, in exec_stored_procedure
    cursor.execute(sql)
Error: ('08004', '[08004] [Microsoft][ODBC SQL Server Driver][SQL Server]The server principal "TDLPATHOLOGY\\cekin" is not able to access the database "RFH_BIO_DW" under the current security context. (916) (SQLExecDirectW)')
-----07/10/2015 23:33
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 218, in dashboard
    data = sql.exec_stored_procedure('spGlobalsApp_AllSystemStats')
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 19, in exec_stored_procedure
    cursor.execute(sql)
Error: ('08004', '[08004] [Microsoft][ODBC SQL Server Driver][SQL Server]The server principal "TDLPATHOLOGY\\cekin" is not able to access the database "RFH_BIO_DW" under the current security context. (916) (SQLExecDirectW)')
-----07/10/2015 23:36
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 218, in dashboard
    data = sql.exec_stored_procedure('spGlobalsApp_AllSystemStats')
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 19, in exec_stored_procedure
    cursor.execute(sql)
Error: ('08004', '[08004] [Microsoft][ODBC SQL Server Driver][SQL Server]The server principal "TDLPATHOLOGY\\cekin" is not able to access the database "RFH_BIO_DW" under the current security context. (916) (SQLExecDirectW)')
-----07/10/2015 23:37
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 218, in dashboard
    data = sql.exec_stored_procedure('spGlobalsApp_AllSystemStats')
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 19, in exec_stored_procedure
    cursor.execute(sql)
Error: ('08004', '[08004] [Microsoft][ODBC SQL Server Driver][SQL Server]The server principal "TDLPATHOLOGY\\cekin" is not able to access the database "RFH_BIO_DW" under the current security context. (916) (SQLExecDirectW)')
-----07/10/2015 23:37
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 218, in dashboard
    data = sql.exec_stored_procedure('spGlobalsApp_AllSystemStats')
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 19, in exec_stored_procedure
    cursor.execute(sql)
Error: ('08004', '[08004] [Microsoft][ODBC SQL Server Driver][SQL Server]The server principal "TDLPATHOLOGY\\cekin" is not able to access the database "RFH_BIO_DW" under the current security context. (916) (SQLExecDirectW)')
-----07/10/2015 23:38
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 218, in dashboard
    data = sql.exec_stored_procedure('spGlobalsApp_AllSystemStats')
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 19, in exec_stored_procedure
    cursor.execute(sql)
Error: ('08004', '[08004] [Microsoft][ODBC SQL Server Driver][SQL Server]The server principal "TDLPATHOLOGY\\cekin" is not able to access the database "RFH_BIO_DW" under the current security context. (916) (SQLExecDirectW)')
-----07/10/2015 23:38
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 218, in dashboard
    data = sql.exec_stored_procedure('spGlobalsApp_AllSystemStats')
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 19, in exec_stored_procedure
    cursor.execute(sql)
Error: ('08004', '[08004] [Microsoft][ODBC SQL Server Driver][SQL Server]The server principal "TDLPATHOLOGY\\cekin" is not able to access the database "RFH_BIO_DW" under the current security context. (916) (SQLExecDirectW)')
-----07/10/2015 23:41
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 218, in dashboard
    data = sql.exec_stored_procedure('spGlobalsApp_AllSystemStats')
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 19, in exec_stored_procedure
    cursor.execute(sql)
Error: ('HY007', '[HY007] [Microsoft][ODBC SQL Server Driver]Associated statement is not prepared (0) (SQLNumResultCols)')
-----07/10/2015 23:41
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 218, in dashboard
    data = sql.exec_stored_procedure('spGlobalsApp_AllSystemStats')
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 19, in exec_stored_procedure
    cursor.execute(sql)
Error: ('HY007', '[HY007] [Microsoft][ODBC SQL Server Driver]Associated statement is not prepared (0) (SQLNumResultCols)')
-----07/10/2015 23:41
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 218, in dashboard
    data = sql.exec_stored_procedure('spGlobalsApp_AllSystemStats')
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 19, in exec_stored_procedure
    cursor.execute(sql)
Error: ('HY007', '[HY007] [Microsoft][ODBC SQL Server Driver]Associated statement is not prepared (0) (SQLNumResultCols)')
-----07/10/2015 23:48
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 218, in dashboard
    data = sql.exec_stored_procedure('spGlobalsApp_AllSystemStats')
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 21, in exec_stored_procedure
    cursor.execute(sql)
Error: ('HY007', '[HY007] [Microsoft][ODBC SQL Server Driver]Associated statement is not prepared (0) (SQLNumResultCols)')
-----07/10/2015 23:48
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 218, in dashboard
    data = sql.exec_stored_procedure('spGlobalsApp_AllSystemStats')
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 21, in exec_stored_procedure
    cursor.execute(sql)
Error: ('HY007', '[HY007] [Microsoft][ODBC SQL Server Driver]Associated statement is not prepared (0) (SQLNumResultCols)')
-----07/10/2015 23:50
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 218, in dashboard
    data = sql.exec_stored_procedure('spGlobalsApp_AllSystemStats')
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 21, in exec_stored_procedure
    cursor.execute(sql)
Error: ('HY007', '[HY007] [Microsoft][ODBC SQL Server Driver]Associated statement is not prepared (0) (SQLNumResultCols)')
-----23/10/2015 17:10
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 221, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----23/10/2015 17:11
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 221, in dashboard
    for row in data:
TypeError: string indices must be integers, not str
-----23/10/2015 17:12
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 222, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----23/10/2015 17:20
Error executing spGlobalsApp_GlobalEditor:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 248, in globalseditor
    result = sql.exec_stored_procedure_list('spGlobalsApp_GlobalEditor', None, True)
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 35, in exec_stored_procedure_list
    for a in arguements:
TypeError: 'NoneType' object is not iterable
-----23/10/2015 17:21
Error executing spGlobalsApp_GlobalEditor:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 248, in globalseditor
    result = sql.exec_stored_procedure_list('spGlobalsApp_GlobalEditor', [], True)
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 35, in exec_stored_procedure_list
    for a in arguements:
TypeError: 'NoneType' object is not iterable
-----23/10/2015 17:21
Error executing spGlobalsApp_GlobalEditor:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 248, in globalseditor
    result = sql.exec_stored_procedure_list('spGlobalsApp_GlobalEditor', [], True)
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 35, in exec_stored_procedure_list
    for a in arguements:
TypeError: 'NoneType' object is not iterable
-----23/10/2015 17:22
Error executing spGlobalsApp_GlobalEditor:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 248, in globalseditor
    result = sql.exec_stored_procedure_list('spGlobalsApp_GlobalEditor', header_row=True)
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 53, in exec_stored_procedure_list
    print 'Problem with ', raw_data[i][j]
  File "C:\Anaconda\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u2010' in position 8: character maps to <undefined>
-----23/10/2015 17:22
Error executing spGlobalsApp_GlobalEditor:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 248, in globalseditor
    result = sql.exec_stored_procedure_list('spGlobalsApp_GlobalEditor', header_row=True)
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 53, in exec_stored_procedure_list
    print 'Problem with ', raw_data[i][j]
  File "C:\Anaconda\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u2010' in position 8: character maps to <undefined>
-----23/10/2015 17:23
Error executing spGlobalsApp_GlobalEditor:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 248, in globalseditor
    result = sql.exec_stored_procedure_list('spGlobalsApp_GlobalEditor', header_row=True)
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 53, in exec_stored_procedure_list
    print 'Problem with ', raw_data[i][j]
  File "C:\Anaconda\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u2010' in position 8: character maps to <undefined>
-----23/10/2015 17:24
Error executing spGlobalsApp_GlobalEditor:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 248, in globalseditor
    result = sql.exec_stored_procedure_list('spGlobalsApp_GlobalEditor', header_row=True)
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 53, in exec_stored_procedure_list
    print 'Problem with ', raw_data[i][j]
  File "C:\Anaconda\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u2010' in position 8: character maps to <undefined>
-----23/10/2015 17:27
Error executing spGlobalsApp_GlobalEditor:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 248, in globalseditor
    result = sql.exec_stored_procedure_list('spGlobalsApp_GlobalEditor', header_row=True)
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 54, in exec_stored_procedure_list
    print 'Problem with ', raw_data[i][j]
  File "C:\Anaconda\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u2010' in position 8: character maps to <undefined>
-----25/10/2015 10:17
Error executing spGlobalsApp_GlobalEditor:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 260, in globalseditordata
    result = sql.exec_stored_procedure_list('spGlobalsApp_GlobalEditor', arguements=[department], header_row=False)
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 45, in exec_stored_procedure_list
    raw_data = cursor.fetchall()
ProgrammingError: No results.  Previous SQL was not a query.
-----25/10/2015 10:18
Error executing spGlobalsApp_GlobalEditor:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 260, in globalseditordata
    result = sql.exec_stored_procedure_list('spGlobalsApp_GlobalEditor', arguements=[department], header_row=False)
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 46, in exec_stored_procedure_list
    raw_data = cursor.fetchall()
ProgrammingError: No results.  Previous SQL was not a query.
-----25/10/2015 10:22
Error executing spGlobalsApp_GlobalEditor:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 261, in globalseditordata
    result = sql.exec_stored_procedure_list('spGlobalsApp_GlobalEditor', [department])
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 46, in exec_stored_procedure_list
    raw_data = cursor.fetchall()
ProgrammingError: No results.  Previous SQL was not a query.
-----25/10/2015 10:23
Error executing spGlobalsApp_GlobalEditor:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 261, in globalseditordata
    result = sql.exec_stored_procedure_list('spGlobalsApp_GlobalEditor')
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 45, in exec_stored_procedure_list
    cursor.execute(sql)
ProgrammingError: ('42000', "[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Procedure or function 'spGlobalsApp_GlobalEditor' expects parameter '@department', which was not supplied. (201) (SQLExecDirectW)")
-----25/10/2015 10:24
Error executing spGlobalsApp_GlobalEditor:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 261, in globalseditordata
    result = sql.exec_stored_procedure_list('spGlobalsApp_GlobalEditor')
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 46, in exec_stored_procedure_list
    raw_data = cursor.fetchall()
ProgrammingError: No results.  Previous SQL was not a query.
-----25/10/2015 10:31
Error executing spGlobalsApp_GlobalEditor:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 261, in globalseditordata
    result = sql.exec_stored_procedure_list('spGlobalsApp_GlobalEditor')
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 46, in exec_stored_procedure_list
    raw_data = cursor.fetchall()
ProgrammingError: No results.  Previous SQL was not a query.
-----25/10/2015 10:50
Error executing spGlobalsApp_GlobalEditor:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 261, in globalseditordata
    result = sql.exec_stored_procedure_list('spGlobalsApp_GlobalEditor')
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 46, in exec_stored_procedure_list
    raw_data = cursor.fetchall()
ProgrammingError: No results.  Previous SQL was not a query.
-----25/10/2015 10:52
Error executing spGlobalsApp_GlobalEditor:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 261, in globalseditordata
    result = sql.exec_stored_procedure_list('spGlobalsApp_GlobalEditor')
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 46, in exec_stored_procedure_list
    raw_data = cursor.fetchall()
ProgrammingError: No results.  Previous SQL was not a query.
-----25/10/2015 10:53
Error executing spGlobalsApp_GlobalEditor:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 261, in globalseditordata
    result = sql.exec_stored_procedure_list('spGlobalsApp_GlobalEditor')
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 46, in exec_stored_procedure_list
    raw_data = cursor.fetchall()
ProgrammingError: No results.  Previous SQL was not a query.
-----25/10/2015 11:47
Error executing spGlobalsApp_GlobalEditor:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 261, in globalseditordata
    result = sql.exec_stored_procedure_list('spGlobalsApp_GlobalEditor',[department])
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 41, in exec_stored_procedure_list
    sql = "EXEC %s %s;" % (stored_procedure,','.join(args))
TypeError: sequence item 0: expected string, NoneType found
-----25/10/2015 22:59
Error executing spGlobalsApp_GlobalEditor_DeptList:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 290, in globals_department_list
    departments = sql.exec_stored_procedure_list('spGlobalsApp_GlobalEditor_DeptList')
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 45, in exec_stored_procedure_list
    cursor.execute(sql)
ProgrammingError: ('42000', "[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Could not find stored procedure 'spGlobalsApp_GlobalEditor_DeptList'. (2812) (SQLExecDirectW)")
-----25/10/2015 23:21
Error executing spGlobalsApp_GlobalEditor:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 282, in pull_all_tfcs_to_one_table
    result = sql.exec_stored_procedure('spGlobalsApp_GlobalCodeDetail_LoadAllTFCs')
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 19, in exec_stored_procedure
    headers = [column[0] for column in cursor.description]
TypeError: 'NoneType' object is not iterable
-----25/10/2015 23:23
Error executing spGlobalsApp_GlobalEditor:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 282, in pull_all_tfcs_to_one_table
    result = sql.exec_stored_procedure('spGlobalsApp_GlobalCodeDetail_LoadAllTFCs')
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 19, in exec_stored_procedure
    headers = [column[0] for column in cursor.description]
TypeError: 'NoneType' object is not iterable
-----25/10/2015 23:25
Error executing spGlobalsApp_GlobalEditor:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 282, in pull_all_tfcs_to_one_table
    result = sql.exec_stored_procedure('spGlobalsApp_GlobalCodeDetail_LoadAllTFCs')
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 19, in exec_stored_procedure
    headers = [column[0] for column in cursor.description]
TypeError: 'NoneType' object is not iterable
-----26/10/2015 20:14
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:15
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:16
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:16
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:16
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:16
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:20
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:22
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:25
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:25
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:28
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:29
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:31
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:32
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:33
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:34
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:35
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:36
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:38
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:40
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:40
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:40
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:41
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:42
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:42
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:51
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:53
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:53
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:53
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:55
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:55
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 21:01
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 262, in dashboard_getdata
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 21:01
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 262, in dashboard_getdata
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 21:02
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 261, in dashboard_getdata
    for row in data:
NameError: global name 'data' is not defined
-----26/10/2015 21:03
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 261, in dashboard_getdata
    for row in data:
NameError: global name 'data' is not defined
-----26/10/2015 21:04
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 261, in dashboard_getdata
    for row in data:
NameError: global name 'data' is not defined
-----26/10/2015 21:05
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 261, in dashboard_getdata
    for row in data:
NameError: global name 'data' is not defined
-----26/10/2015 21:06
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 261, in dashboard_getdata
    for row in data:
NameError: global name 'data' is not defined
-----26/10/2015 21:06
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 261, in dashboard_getdata
    for row in data:
NameError: global name 'data' is not defined
-----26/10/2015 21:07
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 262, in dashboard_getdata
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 21:09
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 263, in dashboard_getdata
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 21:27
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 266, in dashboard_getdata
    summary[system][0] += row[2]
TypeError: unsupported operand type(s) for +=: 'int' and 'str'
-----08/11/2015 22:09
Error reciving global code submission:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 381, in global_edit_submit_changes
    lookup = sql.exec_stored_procedure('spGlobalsApp_GlobalCodeDetail_Info',[code])['result']
NameError: global name 'code' is not defined
-----08/11/2015 22:26
Error reciving global code submission:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 386, in global_edit_submit_changes
    print request.form[r]
  File "C:\Anaconda\lib\site-packages\werkzeug\datastructures.py", line 393, in __getitem__
    raise exceptions.BadRequestKeyError(key)
BadRequestKeyError: 400: Bad Request
-----08/11/2015 22:29
Error reciving global code submission:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 387, in global_edit_submit_changes
    if lookup[r] <> request.form[r]:
  File "C:\Anaconda\lib\site-packages\werkzeug\datastructures.py", line 393, in __getitem__
    raise exceptions.BadRequestKeyError(key)
BadRequestKeyError: 400: Bad Request
-----08/11/2015 22:51
Error reciving global code submission:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 392, in global_edit_submit_changes
    update_global_code_fields(code, updates)
NameError: global name 'update_global_code_fields' is not defined
-----08/11/2015 22:52
Error reciving global code submission:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 392, in global_edit_submit_changes
    sql.update_global_code_fields(code, updates)
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 233, in update_global_code_fields
    cursor.execute(sql)
ProgrammingError: ('42S22', "[42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'AFP2'. (207) (SQLExecDirectW)")
-----09/11/2015 00:07
Error reciving global code submission:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 410, in global_edit_new_code
    lookup = sql.exec_stored_procedure('spGlobalsApp_GlobalCodeDetail_Info',[code])['result'][0]
IndexError: list index out of range
-----12/11/2015 21:35
Error reciving global code submission:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 392, in global_edit_submit_changes
    sql.update_global_code_fields(code, updates)
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 233, in update_global_code_fields
    cursor.execute(sql)
ProgrammingError: ('42000', "[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Incorrect syntax near the keyword 'where'. (156) (SQLExecDirectW)")
-----12/11/2015 21:35
Error executing spGlobalsApp_GlobalEditor:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 362, in globalcodedetail
    result['info'] = sql.exec_stored_procedure('spGlobalsApp_GlobalCodeDetail_Info',[code])['result']
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 18, in exec_stored_procedure
    cursor.execute(sql)
ProgrammingError: ('42000', "[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Procedure or function 'spGlobalsApp_GlobalCodeDetail_Info' expects parameter '@globalcode', which was not supplied. (201) (SQLExecDirectW)")
-----12/11/2015 21:36
Error reciving global code submission:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 392, in global_edit_submit_changes
    sql.update_global_code_fields(code, updates)
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 233, in update_global_code_fields
    cursor.execute(sql)
ProgrammingError: ('42000', "[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Incorrect syntax near the keyword 'where'. (156) (SQLExecDirectW)")
-----12/11/2015 21:36
Error executing spGlobalsApp_GlobalEditor:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 362, in globalcodedetail
    result['info'] = sql.exec_stored_procedure('spGlobalsApp_GlobalCodeDetail_Info',[code])['result']
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 18, in exec_stored_procedure
    cursor.execute(sql)
ProgrammingError: ('42000', "[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Procedure or function 'spGlobalsApp_GlobalCodeDetail_Info' expects parameter '@globalcode', which was not supplied. (201) (SQLExecDirectW)")
-----12/11/2015 21:36
Error reciving global code submission:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 392, in global_edit_submit_changes
    sql.update_global_code_fields(code, updates)
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 233, in update_global_code_fields
    cursor.execute(sql)
ProgrammingError: ('42000', "[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Incorrect syntax near the keyword 'where'. (156) (SQLExecDirectW)")
-----12/11/2015 21:37
Error reciving global code submission:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 392, in global_edit_submit_changes
    sql.update_global_code_fields(code, updates)
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 233, in update_global_code_fields
    cursor.execute(sql)
ProgrammingError: ('42000', "[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Incorrect syntax near the keyword 'where'. (156) (SQLExecDirectW)")
-----12/11/2015 21:44
Error reciving global code submission:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 392, in global_edit_submit_changes
    sql.update_global_code_fields(code, updates)
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 233, in update_global_code_fields
    cursor.execute(sql)
ProgrammingError: ('42000', "[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Incorrect syntax near the keyword 'where'. (156) (SQLExecDirectW)")
-----12/11/2015 23:21
Error reciving global code submission:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 392, in global_edit_submit_changes
    sql.update_global_code_fields(code, updates, user.email)
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 238, in update_global_code_fields
    cursor.execute(sql)
ProgrammingError: ('42000', "[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Incorrect syntax near 'PARA2'. (102) (SQLExecDirectW)")
-----12/11/2015 23:30
Error reciving global code submission:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 392, in global_edit_submit_changes
    sql.update_global_code_fields(code, updates, user.email)
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 238, in update_global_code_fields
    cursor.execute(sql)
ProgrammingError: ('42000', "[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Incorrect syntax near 'AFP'. (102) (SQLExecDirectW)")
-----12/11/2015 23:33
Error reciving global code submission:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 392, in global_edit_submit_changes
    sql.update_global_code_fields(code, updates, user.email)
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 240, in update_global_code_fields
    cursor.execute(sql)
ProgrammingError: ('42000', "[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Incorrect syntax near 'AFP2'. (102) (SQLExecDirectW)")
-----12/11/2015 23:44
Error reciving global code submission:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 392, in global_edit_submit_changes
    sql.update_global_code_fields(code, updates, user.email)
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 233, in update_global_code_fields
    cursor.execute(sql)
ProgrammingError: ('42000', "[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Incorrect syntax near 'BAFO_Department'. (102) (SQLExecDirectW)")
-----12/11/2015 23:51
Error reciving global code submission:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 392, in global_edit_submit_changes
    sql.update_global_code_fields(code, updates, user.email)
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 231, in update_global_code_fields
    cursor.execute(sql)
ProgrammingError: ('42000', "[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Incorrect syntax near '='. (102) (SQLExecDirectW)")
-----15/11/2015 23:37
Error reciving global code submission:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 415, in global_edit_new_code
    submission = {key: value for (key, value) in request.form}
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 415, in <dictcomp>
    submission = {key: value for (key, value) in request.form}
ValueError: too many values to unpack
-----16/11/2015 00:05
Error reciving global code submission:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 415, in global_edit_new_code
    sql.insert_new_global_code(submission, user.email)
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 256, in insert_new_global_code
    cursor.execute(sql)
ProgrammingError: ('42S22', "[42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'LOINC'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'Description'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'HSL_Code'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'GlobalCode'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'Type'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'PBCL'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'SubSection'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'Sample'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'Interface'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'PrimaryLibrary'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'BAFO_Subsection'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'SNOMEDCT_UK'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'Department'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'MiddlewareCode'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'NLMC'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'BAFO_Department'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'Analyte'. (207)")
-----16/11/2015 00:08
Error reciving global code submission:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 415, in global_edit_new_code
    sql.insert_new_global_code(submission, user.email)
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 256, in insert_new_global_code
    cursor.execute(sql)
ProgrammingError: ('42S22', "[42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'LOINC'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'Description'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'HSL_Code'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'GlobalCode'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'Type'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'PBCL'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'SubSection'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'Sample'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'Interface'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'PrimaryLibrary'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'BAFO_Subsection'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'SNOMEDCT_UK'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'Department'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'MiddlewareCode'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'NLMC'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'BAFO_Department'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'Analyte'. (207)")
-----16/11/2015 00:10
Error reciving global code submission:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 415, in global_edit_new_code
    sql.insert_new_global_code(submission, user.email)
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 259, in insert_new_global_code
    cursor.execute(sql)
ProgrammingError: ('42S22', "[42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'LOINC'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'Description'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'HSL_Code'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'GlobalCode'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'Type'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'PBCL'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'SubSection'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'Sample'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'Interface'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'PrimaryLibrary'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'BAFO_Subsection'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'SNOMEDCT_UK'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'Department'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'MiddlewareCode'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'NLMC'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'BAFO_Department'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'Analyte'. (207)")
-----16/11/2015 00:14
Error reciving global code submission:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 415, in global_edit_new_code
    sql.insert_new_global_code(submission, user.email)
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 259, in insert_new_global_code
    cursor.execute(sql)
ProgrammingError: ('42S22', "[42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'LOINC, Description, HSL_Code, GlobalCode, Type, PBCL, SubSection, Sample, Interface, PrimaryLibrary, BAFO_Subsection, SNOMEDCT_UK, Department, MiddlewareCode, NLMC, BAFO_Department, Analyte'. (207) (SQLExecDirectW)")
-----16/11/2015 00:21
Error reciving global code submission:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 415, in global_edit_new_code
    sql.insert_new_global_code(submission, user.email)
TypeError: insert_new_global_code() takes exactly 3 arguments (2 given)
-----16/11/2015 00:33
Error reciving global code submission:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 419, in global_edit_new_code
    result['info'] = sql.exec_stored_procedure('spGlobalsApp_GlobalCodeDetail_Info',[code])['result']
NameError: global name 'code' is not defined
-----17/11/2015 19:36
Error deleting global code:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 441, in global_edit_delete_code
    sql.exec_stored_procedure_list('spGlobalsApp_DeleteGlobalCode',[code, exclusion, user.email])
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 46, in exec_stored_procedure_list
    raw_data = cursor.fetchall()
ProgrammingError: No results.  Previous SQL was not a query.
-----17/11/2015 19:37
Error deleting global code:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 441, in global_edit_delete_code
    sql.exec_stored_procedure_list('spGlobalsApp_DeleteGlobalCode',[code, exclusion, user.email])
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 46, in exec_stored_procedure_list
    raw_data = cursor.fetchall()
ProgrammingError: No results.  Previous SQL was not a query.
-----17/11/2015 19:39
Error executing code detail lookup:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 362, in globalcodedetail
    result['info'] = sql.exec_stored_procedure('spGlobalsApp_GlobalCodeDetail_Info',[code])['result']
TypeError: string indices must be integers, not str
-----17/11/2015 19:42
Error deleting global code:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 441, in global_edit_delete_code
    sql.exec_stored_procedure_list('spGlobalsApp_DeleteGlobalCode',[code, exclusion, user.email], return_value = True)
TypeError: exec_stored_procedure_list() got an unexpected keyword argument 'return_value'
-----17/11/2015 19:43
Error deleting global code:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 441, in global_edit_delete_code
    sql.exec_stored_procedure_list('spGlobalsApp_DeleteGlobalCode',[code, exclusion, user.email])
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 61, in exec_stored_procedure_list
    raw_data = cursor.fetchall()
ProgrammingError: No results.  Previous SQL was not a query.
-----17/11/2015 19:43
Error deleting global code:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 441, in global_edit_delete_code
    sql.exec_stored_procedure_noreturn('spGlobalsApp_DeleteGlobalCode',[code, exclusion, user.email])
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 36, in exec_stored_procedure_noreturn
    cursor.execute(sql)
ProgrammingError: ('42000', "[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Incorrect syntax near the keyword 'Not'. (156) (SQLExecDirectW)")
-----18/11/2015 16:49
Error getting TLC list:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 75, in tlc_data
    result = sql.exec_stored_procedure_list('spGlobalsApp_GetTLCList',args)
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 60, in exec_stored_procedure_list
    cursor.execute(sql)
ProgrammingError: ('42000', "[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Incorrect syntax near 'A'. (102) (SQLExecDirectW)")
-----18/11/2015 16:49
Error getting TLC list:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 75, in tlc_data
    result = sql.exec_stored_procedure_list('spGlobalsApp_GetTLCList',args)
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 60, in exec_stored_procedure_list
    cursor.execute(sql)
ProgrammingError: ('42000', "[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Incorrect syntax near 'A'. (102) (SQLExecDirectW)")
-----18/11/2015 16:50
Error getting TLC list:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 75, in tlc_data
    result = sql.exec_stored_procedure_list('spGlobalsApp_GetTLCList',args)
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 60, in exec_stored_procedure_list
    cursor.execute(sql)
ProgrammingError: ('42000', "[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Incorrect syntax near 'A'. (102) (SQLExecDirectW)")
-----18/11/2015 17:13
Error getting new TFCs in the mapping table:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 69, in get_new_tfc
    sql.exec_stored_procedure_noreturn('spGlobalsApp_GetNewTFC',[])
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 36, in exec_stored_procedure_noreturn
    cursor.execute(sql)
ProgrammingError: ('42000', '[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Procedure spGlobalsApp_GetNewTFC has no parameters and arguments were supplied. (8146) (SQLExecDirectW)')
-----18/11/2015 17:13
Error getting new TFCs in the mapping table:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 69, in get_new_tfc
    sql.exec_stored_procedure_noreturn('spGlobalsApp_GetNewTFC',[])
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 36, in exec_stored_procedure_noreturn
    cursor.execute(sql)
ProgrammingError: ('42000', '[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Procedure spGlobalsApp_GetNewTFC has no parameters and arguments were supplied. (8146) (SQLExecDirectW)')
-----18/11/2015 17:14
Error getting new TFCs in the mapping table:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 69, in get_new_tfc
    sql.exec_stored_procedure_noreturn('spGlobalsApp_GetNewTFC')
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 36, in exec_stored_procedure_noreturn
    cursor.execute(sql)
ProgrammingError: ('42000', '[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Procedure spGlobalsApp_GetNewTFC has no parameters and arguments were supplied. (8146) (SQLExecDirectW)')
-----18/11/2015 17:15
Error getting new TFCs in the mapping table:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 69, in get_new_tfc
    sql.exec_stored_procedure_noreturn('spGlobalsApp_GetNewTFC')
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 38, in exec_stored_procedure_noreturn
    cursor.execute(sql)
ProgrammingError: ('42000', '[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Procedure spGlobalsApp_GetNewTFC has no parameters and arguments were supplied. (8146) (SQLExecDirectW)')
